# Workflow metadata and documentation
# Learn more about the next generation of Helios Pipelines here:
# https://rbcgithub.fg.rbc.com/pages/rbc-to/adeo-helios-docs/

# Name of the GitHub Actions workflow
name: Helios Docker Build Pipeline

# Triggers for the workflow
# Workflow will trigger on push events
on:
  push:
    # Match every branch
    branches:
      - '*'

  # Workflow will trigger on pull request events
  pull_request:
    # Match every branch
    branches:
      - '*'

  # Manual trigger via GitHub UI
  workflow_dispatch:

# Start defining all the jobs
jobs:
  # ------------------------------------------
  # Job 1: Initialization
  # Purpose: Set context values and export them
  # ------------------------------------------
  initialization:
    # Name of the job
    name: Initialization
    # Runner on which this job should execute
    runs-on: ghes-runners-standard

    # Declare outputs to be passed to downstream jobs
    outputs:
      # Set the Dockerfile path
      dockerfile: Dockerfile
      # Set the Docker repository name dynamically
      docker_repository: ${{ steps.helios_context.outputs.app_code_lowercase }}-dev

    # Steps to run in this job
    steps:
      # Step to initialize Helios context (fetching metadata like app_code)
      - name: Initialization
        id: helios_context
        # Use the shared Helios context action
        uses: rbc-to/adeo-helios-context-action@v1
        with:
          # Provide GitHub context to the action
          github_context: ${{ toJSON(github) }}

  # ------------------------------------------
  # Job 2: Docker Build
  # Purpose: Build the Docker image using standard template
  # ------------------------------------------
  docker_build:
    # Learn more about configuring this job here:
    # https://rbcgithub.fg.rbc.com/rbc-to/adeo-helios-workflows/blob/main/docs/ci/build_docker.readme.md
    # Reusable workflow for building Docker image
    uses: rbc-cm/helios-workflows/.github/workflows/build_docker.yml@main
    # Job dependency: wait for initialization to finish
    needs: initialization
    # Pass dynamic values as inputs to the reusable build workflow
    with:
      # Dockerfile path passed from initialization job
      dockerfile: ${{ needs.initialization.outputs.dockerfile }}
      # Docker repository passed from initialization job
      docker_repository: ${{ needs.initialization.outputs.docker_repository }}

  # ------------------------------------------
  # Job 3: Aqua Security Scan (Optional)
  # Purpose: Scan the built image for vulnerabilities
  # ------------------------------------------
  aqua_scan:
    # Learn more about configuring this job here:
    # https://rbcgithub.fg.rbc.com/rbc-to/adeo-helios-workflows/blob/main/docs/ci/aqua_scan.readme.md
    # Reusable workflow for performing Aqua scan
    uses: rbc-cm/helios-workflows/.github/workflows/aqua_scan.yml@main
    # Job dependency: wait for Docker build to complete
    needs: docker_build
    # Pass the image location to be scanned
    with:
      images: ${{ format('{0}', needs.docker_build.outputs.image_location) }}
