# --------------------------------------------
# Helios Docker Build Pipeline (Pattern 1)
# --------------------------------------------

# This workflow builds a Docker image and optionally performs a security scan
# It uses shared Helios reusable workflows for standardized steps

name: Helios Docker Build Pipeline

on:
  # Trigger this workflow on every push and pull request to any branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Also allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  # -------------------------------
  # Job 1: Initialization
  # -------------------------------
  initialization:
    name: Initialization
    runs-on: ghes-runners-standard

    # Outputs values used by later jobs
    outputs:
      dockerfile: Dockerfile
      docker_repository: ${{ steps.helios_context.outputs.app_code_lowercase }}-dev

    steps:
      - name: Initialization
        id: helios_context
        uses: rbc-cm/adeo-helios-context-action@v1
        with:
          github_context: ${{ toJSON(github) }}

  # -------------------------------
  # Job 2: Docker Build
  # -------------------------------
  docker_build:
    name: Docker Build
    needs: initialization
    uses: rbc-cm/helios-workflows/.github/workflows/build_docker.yml@main
    with:
      dockerfile: ${{ needs.initialization.outputs.dockerfile }}
      docker_repository: ${{ needs.initialization.outputs.docker_repository }}

  # -------------------------------
  # Job 3: Aqua Security Scan (Optional)
  # -------------------------------
  aqua_scan:
    name: Aqua Scan
    needs: docker_build
    uses: rbc-cm/helios-workflows/.github/workflows/aqua_scan.yml@main
    with:
      images: ${{ format('{0}', needs.docker_build.outputs.image_location) }}
